[package]
name = "mobi_android_collector"
version = "0.0.1"
edition = "2021"
description = "Android on-device artifact collector (vendored from CERT-EDF/rusty-magpie)"
license = "Apache-2.0"
repository = "https://github.com/CERT-EDF/rusty-magpie"

[[bin]]
name = "rusty_magpie"
path = "src/main.rs"

[features]
default = ["ps", "find"]
ps = []
find = []
yara = ["dep:yara-x"]

[dependencies]
anyhow = "1.0"
log = "0.4.21"
env_logger = { version = "0.11.8", features = ["auto-color"] }
clap = { version = "4.5.47", features = ["cargo", "derive"] }
yara-x = { version = "1.5.0", features = ["logging"], optional = true }
globwalk = "0.9.1"
crossbeam = "0.8"
serde_json = { version = "1.0.141" }
serde = { version = "1.0.219", features = ["derive"] }
jwalk-meta = "0.9"
wild = "2.2.1"
flume = "0.11"
glob-sl = "0.4"
sha2 = { version = "0.10.9", default-features = true }
base16ct = { version = "0.3.0", features = ["alloc"] }
procfs = "0.17.0"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
